# -*- coding: utf-8 -*-
"""
/***************************************************************************
                                 A QGIS plugin
 dbprisk2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-12
        copyright            : (C) 2025 by KIOS Smart Water Team
        email                : mkiria01@ucy.ac.cy
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import importlib
from typing import List

# -------- Minimal additions: rewrite/run .bat and check requirements ----------
import os
import re
import subprocess
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import QgsMessageLog, Qgis, QgsApplication
# -----------------------------------------------------------------------------

PLUGIN_TAG = "dbpRisk"

def log(msg, lvl=Qgis.Info):
    QgsMessageLog.logMessage(str(msg), PLUGIN_TAG, lvl)

SUBPLUGINS = ["dbpriskapp", "dbpSimulatorUI"]

_REQ_LINE = re.compile(r"^\s*([A-Za-z0-9._-]+)(?:\[.*?\])?\s*([<>=!~]=?.*)?$")

def _requirements_file() -> str:
    """Absolute path to installpackages/requirements.txt (next to this file)."""
    install_dir = os.path.join(os.path.dirname(__file__), "installpackages")
    return os.path.join(install_dir, "requirements.txt")

def _parse_requirement_names(req_file: str):
    """
    Return just the distribution names (no versions).
    If the file is missing or unreadable, return [] silently (no warnings).
    """
    try:
        if not os.path.isfile(req_file):
            return []
        names = []
        with open(req_file, "r", encoding="utf-8", errors="ignore") as f:
            for raw in f:
                s = raw.strip()
                if not s or s.startswith("#"):
                    continue
                # Skip direct URLs or local wheels
                if s.startswith(("http://", "https://")) or s.endswith((".whl", ".zip", ".tar.gz")):
                    if "#egg=" in s:  # best-effort
                        names.append(s.split("#egg=", 1)[1])
                    continue
                m = _REQ_LINE.match(s)
                if m:
                    names.append(m.group(1))
        return names
    except Exception:
        # Silent skip on any error
        return []

def _missing_imports(req_file: str):
    """
    Try importing modules for each requirement (dash->underscore). If import fails, mark missing.
    Version specs are ignored; installer handles versions.
    """
    missing = []
    for dist in _parse_requirement_names(req_file):
        modname = dist.replace("-", "_")
        try:
            importlib.import_module(modname)
        except Exception:
            missing.append(dist)
    return missing
# -----------------------------------------------------------------------------


def _write_installer_bat(install_dir: str) -> str:
    """
    Create/overwrite the installer .bat inside installpackages/
    so it uses the *current* QGIS the user is running.
    Returns the full path to the .bat.
    """
    qgis_prefix = QgsApplication.prefixPath()
    qgis_root = os.path.normpath(os.path.join(qgis_prefix, "..", ".."))
    bin_dir = os.path.join(qgis_root, "bin")

    python_exe = os.path.join(bin_dir, "python3.exe")
    if not os.path.exists(python_exe):
        python_exe = os.path.join(bin_dir, "python.exe")

    bat_path = os.path.join(install_dir, "py3-env.bat")  # your single .bat to keep/change
    bat = f"""@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

REM Auto-generated by plugin to match the running QGIS version.
SET "OSGEO4W_ROOT={qgis_root}"
SET "QGIS_PREFIX_PATH={qgis_prefix}"
SET "PATH=%OSGEO4W_ROOT%\\bin;%PATH%"

IF EXIST "%OSGEO4W_ROOT%\\bin\\o4w_env.bat" CALL "%OSGEO4W_ROOT%\\bin\\o4w_env.bat"
IF EXIST "%OSGEO4W_ROOT%\\bin\\qt5_env.bat" CALL "%OSGEO4W_ROOT%\\bin\\qt5_env.bat"

REM Ensure QGIS libs/plugins on PATH
SET "PATH=%QGIS_PREFIX_PATH%\\bin;%PATH%"
SET "QT_PLUGIN_PATH=%QGIS_PREFIX_PATH%\\qtplugins;%QT_PLUGIN_PATH%"

REM Use Python that ships with this QGIS
SET "PYEXE={python_exe}"

REM Bootstrap pip and install from requirements.txt next to this .bat
"%PYEXE%" -m ensurepip --upgrade
"%PYEXE%" -m pip install --upgrade pip
"%PYEXE%" -m pip install -r "%~dp0requirements.txt"

ENDLOCAL
"""
    try:
        with open(bat_path, "w", encoding="utf-8") as f:
            f.write(bat)
        log(f"Installer .bat updated for this QGIS at: {bat_path}")
    except Exception as e:
        log(f"Failed to write {bat_path}: {e}", Qgis.Critical)
    return bat_path


def _run_installer_bat(install_dir: str) -> bool:
    """
    Run the installer .bat and return True if the process exit code == 0.
    """
    bat_path = _write_installer_bat(install_dir)
    try:
        proc = subprocess.run(
            ["cmd.exe", "/C", bat_path],
            check=False,
            capture_output=True,
            text=True,
            cwd=install_dir
        )
        if proc.stdout:
            log(proc.stdout)
        if proc.stderr:
            log(proc.stderr, Qgis.Warning)
        return proc.returncode == 0
    except Exception as e:
        log(f"Running installer .bat failed: {e}", Qgis.Critical)
        return False
# -----------------------------------------------------------------------------


class _Wrap:
    def __init__(self, iface, pkg: str):
        self.iface = iface
        self.pkg = pkg
        self.mod = None
        self.inst = None

    def load(self) -> bool:
        try:
            self.mod = importlib.import_module(f".{self.pkg}", __package__)
        except Exception as e:
            log(f"Import failed for '{self.pkg}': {e}", Qgis.Critical)
            return False
        if not hasattr(self.mod, "classFactory"):
            log(f"'{self.pkg}' missing classFactory(iface)", Qgis.Critical)
            return False
        try:
            self.inst = self.mod.classFactory(self.iface)
        except Exception as e:
            log(f"classFactory() error in '{self.pkg}': {e}", Qgis.Critical)
            return False
        return True

    def init_gui(self):
        if hasattr(self.inst, "initGui"):
            try:
                self.inst.initGui()
                log(f"initGui OK: {self.pkg}")
            except Exception as e:
                log(f"initGui failed: {self.pkg}: {e}", Qgis.Critical)

    def unload(self):
        if hasattr(self.inst, "unload"):
            try:
                self.inst.unload()
                log(f"unload OK: {self.pkg}")
            except Exception as e:
                log(f"unload failed: {self.pkg}: {e}", Qgis.Critical)


class dbpRisk2Plugin:
    def __init__(self, iface):
        self.iface = iface
        self.children: List[_Wrap] = []

    def _ensure_requirements(self) -> bool:
        """
        Only prompt/install if imports are actually missing.
        Re-check after install; return True if everything importable.
        If requirements.txt is absent or unreadable, skip quietly.
        """
        install_dir = os.path.join(os.path.dirname(__file__), "installpackages")
        req_file = _requirements_file()

        missing = _missing_imports(req_file)
        if not missing:
            return True

        # Ask user for permission
        msg = QMessageBox(self.iface.mainWindow())
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Install Python packages")
        msg.setText(
            "This plugin needs some Python packages that aren’t installed:\n\n"
            + "\n".join(missing)
            + f"\n\nInstall them now for the current QGIS?"
            + f"\n\n(Detected QGIS: {Qgis.QGIS_VERSION})"
        )
        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        if msg.exec() != QMessageBox.Yes:
            log("User declined to install missing packages.", Qgis.Warning)
            return False

        ok = _run_installer_bat(install_dir)
        if not ok:
            QMessageBox.critical(self.iface.mainWindow(), "Installation failed",
                                 "The installer did not complete successfully. See QGIS Logs for details.")
            return False

        missing_after = _missing_imports(req_file)
        if not missing_after:
            QMessageBox.information(self.iface.mainWindow(), "Packages installed",
                                    "Required packages were installed successfully.\n"
                                    "If anything still fails to import, please restart QGIS.")
            return True

        QMessageBox.critical(self.iface.mainWindow(), "Packages still missing",
                             "Some packages still could not be imported after installation:\n\n"
                             + "\n".join(missing_after)
                             + "\n\nPlease check the QGIS Logs for details.")
        return False

    def initGui(self):
        self._ensure_requirements()

        for name in SUBPLUGINS:
            w = _Wrap(self.iface, name)
            if w.load():
                self.children.append(w)
                w.init_gui()
            else:
                log(f"Skipped '{name}' due to load error", Qgis.Warning)

    def unload(self):
        for w in reversed(self.children):
            w.unload()
        self.children.clear()
