@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

REM Auto-generated by plugin to match the running QGIS version.
SET "OSGEO4W_ROOT=C:\PROGRA~1\QGIS34~1.3"
SET "QGIS_PREFIX_PATH=C:/PROGRA~1/QGIS34~1.3/apps/qgis"
SET "PATH=%OSGEO4W_ROOT%\bin;%PATH%"

IF EXIST "%OSGEO4W_ROOT%\bin\o4w_env.bat" CALL "%OSGEO4W_ROOT%\bin\o4w_env.bat"
IF EXIST "%OSGEO4W_ROOT%\bin\qt5_env.bat" CALL "%OSGEO4W_ROOT%\bin\qt5_env.bat"

REM Ensure QGIS libs/plugins on PATH
SET "PATH=%QGIS_PREFIX_PATH%\bin;%PATH%"
SET "QT_PLUGIN_PATH=%QGIS_PREFIX_PATH%\qtplugins;%QT_PLUGIN_PATH%"

REM Use Python that ships with this QGIS
SET "PYEXE=C:\PROGRA~1\QGIS34~1.3\bin\python3.exe"

REM Bootstrap pip and install from requirements.txt next to this .bat
"%PYEXE%" -m ensurepip --upgrade
"%PYEXE%" -m pip install --upgrade pip
"%PYEXE%" -m pip install -r "%~dp0requirements.txt"

ENDLOCAL
