# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dbpSimulator
                                 A QGIS plugin
 This plugin created for the IntoDBP project.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-20
        copyright            : (C) 2024 by KIOS Water Team
        email                : mkiria01@ucy.ac.cy
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load dbpSimulator class from file dbpSimulator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dbp_simulator import dbpSimulator
    return dbpSimulator(iface)
