# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dbpriskapp
                                 A QGIS plugin
 dbpriskapp
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-12
        copyright            : (C) 2025 by KIOS Smart Water Team
        email                : mkiria01@ucy.ac.cy
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'KIOS Smart Water Team'
__date__ = '2025-06-12'
__copyright__ = '(C) 2025 by KIOS Smart Water Team'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load dbpriskapp class from file dbpriskapp.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dbpriskapp import dbpriskappPlugin
    return dbpriskappPlugin()
